# Generated by Django 4.2.14 on 2024-08-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, verbose_name='Инвентарный номер')),
            ],
            options={
                'verbose_name': 'Инвентарный номер',
                'verbose_name_plural': '(1) Инвентарные номера',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='Owner_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_active', models.CharField(max_length=150, verbose_name='Владелец актива')),
            ],
            options={
                'verbose_name': 'Владелец актива',
                'verbose_name_plural': '(1) Владелецы активов',
                'ordering': ['owner_active'],
            },
        ),
        migrations.CreateModel(
            name='Status_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': '(1) Статусы',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Type_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_active', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Тип актива')),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': '(1) Типы активов',
                'ordering': ['type_active'],
            },
        ),
        migrations.CreateModel(
            name='Name_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('name_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('type_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uchet_active.type_active', verbose_name='Тип актива')),
            ],
            options={
                'verbose_name': 'Модель актива',
                'verbose_name_plural': '(1) Модели активов',
                'ordering': ['type_active', 'manufacturer', 'name_model'],
            },
        ),
    ]
