# Generated by Django 4.2.14 on 2024-08-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet_active', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_number',
            name='inventory_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='owner_active',
            name='owner_active',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Владелец актива'),
        ),
    ]
