# Generated by Django 4.2.14 on 2024-09-07 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet_active', '0002_alter_inventory_number_inventory_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_quantity_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_quantity', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Ед.изм-я')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': '(1) Единицы измерения',
                'ordering': ['name_quantity'],
            },
        ),
        migrations.CreateModel(
            name='Location_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=150, verbose_name='Локация/Склад')),
                ('owner_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uchet_active.owner_active', verbose_name='Владелец актива')),
            ],
            options={
                'verbose_name': 'Локация/Склад',
                'verbose_name_plural': '(1) Локация/Склад',
                'ordering': ['owner_active', 'location'],
            },
        ),
    ]
