# Generated by Django 4.2.14 on 2024-09-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet_active', '0003_name_quantity_active_location_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory_number',
            options={'ordering': ['inventory_number'], 'verbose_name': 'Инвентарный номер', 'verbose_name_plural': '(1.3) Инвентарные номера'},
        ),
        migrations.AlterModelOptions(
            name='location_active',
            options={'ordering': ['owner_active', 'location'], 'verbose_name': 'Локация/Склад', 'verbose_name_plural': '(1.7) Локация/Склад'},
        ),
        migrations.AlterModelOptions(
            name='name_active',
            options={'ordering': ['type_active', 'manufacturer', 'name_model'], 'verbose_name': 'Модель актива', 'verbose_name_plural': '(1.2) Модели активов'},
        ),
        migrations.AlterModelOptions(
            name='name_quantity_active',
            options={'ordering': ['name_quantity'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': '(1.4) Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='owner_active',
            options={'ordering': ['owner_active'], 'verbose_name': 'Владелец актива', 'verbose_name_plural': '(1.6) Владелецы активов'},
        ),
        migrations.AlterModelOptions(
            name='status_active',
            options={'ordering': ['status'], 'verbose_name': 'Статус', 'verbose_name_plural': '(1.5) Статусы'},
        ),
        migrations.AlterModelOptions(
            name='type_active',
            options={'ordering': ['type_active'], 'verbose_name': 'Тип актива', 'verbose_name_plural': '(1.1) Типы активов'},
        ),
    ]
