# Generated by Django 4.2.14 on 2024-09-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uchet_active', '0004_alter_inventory_number_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_active',
            name='manufacturer',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='name_active',
            name='name_model',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='Details_document_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(db_index=True, max_length=50, verbose_name='Документ')),
                ('shipping_location', models.CharField(db_index=True, max_length=150, verbose_name='Локация/Склад отгрузки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('creator_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено/создано')),
            ],
            options={
                'verbose_name': 'Реквизиты документа',
                'verbose_name_plural': '(2.1) Реквизиты документа',
                'ordering': ['name_document', 'shipping_location'],
            },
        ),
    ]
