# Generated by Django 4.2.14 on 2024-09-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet_active', '0005_alter_name_active_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details_document_active',
            options={'ordering': ['name_document', 'shipping_location'], 'verbose_name': 'Реквизиты документа', 'verbose_name_plural': '(2.1) Реквизиты документов'},
        ),
    ]
