# Generated by Django 4.2.14 on 2024-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet_active', '0006_alter_details_document_active_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='Учетная запись')),
                ('fio', models.CharField(max_length=75, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('distingished_name', models.CharField(max_length=175, verbose_name='Имя объекта')),
                ('company', models.CharField(blank=True, max_length=75, verbose_name='Юридическое лицо')),
                ('company_position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('mobile', models.CharField(blank=True, max_length=35, verbose_name='Телефон (мобильный)')),
                ('telephone_number', models.CharField(blank=True, max_length=35, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Профиль пользователя (AD)',
                'verbose_name_plural': '(2.2) Профили пользователей (AD)',
                'ordering': ['account'],
            },
        ),
    ]
